config/routes.rb
Wwii::Application.routes.draw do

  root :to => 'Campaigns#index'

  get "login" => "Sessions#new", as:"login"

  post "login" => "Sessions#create"

  delete "logout"=>"Sessions#destroy", as:"logout"

  get "logout"=>"Sessions#destroy"
  resources :icons
  resources :users
  resources :unit_classes
  resources :operations
  resources :campaigns
  resources :units
  resources :events
  resources :countries
  resources :event_types

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event_date, :name, :lat, :lng, :gmaps , :old_id, :unique_id, :address, :unit_id, :operation_id, :country_id, :event_type_id, :description

  belongs_to :unit
  belongs_to :operation
  belongs_to :country
  belongs_to :event_type

  validates_presence_of :name, :event_date

  acts_as_gmappable :process_geocoding => :geocode?,:lat=>'lat', :lng=>'lng',:address => "address"

  scope :no_planes, lambda { where("event_type_id != ?",EventType.find_by_name("Plane Crash").id).order('event_date asc')}

  scope :with_dates, lambda { where("event_date IS NOT null")}

  def date_formated
    (event_date.strftime('%a, %b %e %Y') unless event_date.nil?) || ""
  end

  def flag_path
      (country.flag_path unless country.nil?) || (unit.country.flag_path unless unit.nil? || unit.country.nil?) || nil
  end

  def calculate_country
    self.unit.country || self.country
  end

  def geocode?
    if !lat.blank? && !lat.blank?
      false
    elsif (lat.blank? || lng.blank?) && !address.blank?
      true
    elsif address_changed?
      true
    else
      false
    end
  end

  def location
     return {lat: lat, lng: lng} unless lat.nil? || lng.nil?
  end

  def gmaps4rails_title
      return event_date.strftime("%b %e %Y") unless event_date.nil?
  end

  def marker_picture
    if self.unit.present? && self.unit.icon.present?
      path = self.unit.icon.path
      folder_path = path.split("_")
      size = folder_path.delete_at(-1).split(".")[0].to_i
      folder_path = "/assets/" + path
      {
        :picture => folder_path,
        :width => size,
        :height => size,
        :marker_anchor => [ size/2, size]
      }
    else
      {
        :picture => "/assets/allies_infantry/allies_infantry_24.png",
        :width => 24,
        :height => 24,
        :marker_anchor => [ 12, 24]
      }
    end
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user, except:[:show]

  def index
    @events = Event.order(:event_date).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @event = Event.find(params[:id])
    @markers = @event.to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @event = Event.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @controller = params[:controller]
    @action = params[:action]
    @event = Event.find(params[:id])
    @markers = @event.to_gmaps4rails
  end

  def create
    @event = Event.create(params[:event])
    if @event.operation.active == false
      @event.update_attributes(active:true)
    end
    @markers = @event.to_gmaps4rails
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    if params[:event][:address].nil?
      params[:event][:address] = nil
    end
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<span class="main-list-item main-list-link">
  <%= event.name %> - <%= event.date_formated %>
</span>

app/views/events/_event_list.html.erb
<h3 class="subtitle">Events</h3>
<div id="events">
  <ul class="main-list" id="events-list">

  </ul>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <p class="notice"><%= @event.errors.full_messages %> </p>
    <%= f.label :name %> <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_area :description, rows:3 %>
    <%= f.label :address %> <%= f.text_field :address %>
    <%= f.label :Latitude %> <%= f.text_field :lat %>
    <%= f.label :Longitude %> <%= f.text_field :lng %>
    <%= f.label :Date %>
    <%= f.date_select :event_date,start_year:1939,end_year:1949, include_blank:true, default:nil %>
    <%= f.label :unit_id %>
    <%= f.collection_select :unit_id, Unit.all, :id, :name, default:nil, include_blank:true %>
    <%= f.label :country_id %>
    <%= f.collection_select :country_id, Country.all, :id,:name, default:nil, include_blank:true %>
    <%= f.label :operation_id %>
    <%= f.collection_select :operation_id, Operation.all, :id,:name, default:nil, include_blank:true %>
    <%= f.label :event_type_id %>
    <%= f.collection_select :event_type_id, EventType.all, :id, :name, default:nil, include_blank:true %><br>
    <%= f.submit %>
<% end %>

app/views/events/_infowindow.html.erb
<div class="gwindow">
  <h5><%= event.name %></h5>
  <h6>on <%= event.date_formated %></h6>
  <p>
    <%= (link_to(image_tag(event.flag_path, width:40,class:"flag",align:"left"), country_path(event.calculate_country))) unless event.calculate_country.nil? %>
    <%= (link_to event.unit.name ,unit_path(event.unit)) unless event.unit.nil? %><br>
    <%= (link_to 'Operation ' + event.operation.name, operation_path(event.operation)) unless event.operation.nil? %>
  </p>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<% content_for :scripts_callback do %>
  <script type="text/javascript" charset="utf-8">
    var markersArray = [];
    Gmaps.map.HandleDragend = function(pos) {
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({
        latLng: pos
      }, function(responses) {
        if (responses && responses.length > 0) {
          //alert(responses[0].formatted_address);
          $("#event_lat").val(pos.lat())
          $("#event_lng").val(pos.lng())
        } else {
        alert('Cannot determine address at this location.');
        }
      });
    };

    Gmaps.map.callback = function() {
      for (var i = 0; i <  this.markers.length; ++i) {
         google.maps.event.addListener(Gmaps.map.markers[i].serviceObject, 'dragend', function() { Gmaps.map.HandleDragend(this.getPosition()) });
      }
    };
  </script>
<% end %>


<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= link_to 'New Event', new_event_path %><table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Event Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Actions</th>
  </thead>

<% @events.each do |event| %>
  <tr>
    <td><%= event.date_formated %></td>
    <td><%= link_to event.name, event %></td>
    <td><%= event.lat %></td>
    <td><%= event.lng %></td>
    <td>
      <%= link_to 'Edit', edit_event_path(event), class:"btn btn-warning" %>
      <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate @events %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h2 class="main-title"><%= @event.name %>
</h2>
<p class="main-text"><%= @event.date_formated %></p>
<ul class="main-list">

  <li class="main-list-item">
    <%= image_tag @event.flag_path %><%= @event.country.name unless @event.country.nil? %>
  </li>
  <li class="main-list-item">
    Unit: <%= @event.unit.name unless @event.unit.nil? %>
  </li>
  <li class="main-list-item">
    Operation: <%= @event.operation.name unless @event.operation.nil? %>
  </li>
  <li class="main-list-item">
    Event Type: <%= @event.event_type.name unless @event.event_type.nil? %>
  </li>
</ul>