config/routes.rb
Wwii::Application.routes.draw do

  root :to => 'Campaigns#index'

  get "login" => "Sessions#new", as:"login"

  post "login" => "Sessions#create"

  delete "logout"=>"Sessions#destroy", as:"logout"

  get "logout"=>"Sessions#destroy"
  resources :icons
  resources :users
  resources :unit_classes
  resources :operations
  resources :campaigns
  resources :units
  resources :events
  resources :countries
  resources :event_types

end

app/controllers/unit_classes_controller.rb
class UnitClassesController < ApplicationController
  before_filter :authenticate_user

  def index
    @unit_classes = UnitClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unit_classes }
    end
  end

  # GET /unit_classes/1
  # GET /unit_classes/1.json
  def show
    @unit_class = UnitClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit_class }
    end
  end

  # GET /unit_classes/new
  # GET /unit_classes/new.json
  def new
    @unit_class = UnitClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit_class }
    end
  end

  # GET /unit_classes/1/edit
  def edit
    @unit_class = UnitClass.find(params[:id])
  end

  # POST /unit_classes
  # POST /unit_classes.json
  def create
    @unit_class = UnitClass.new(params[:unit_class])

    respond_to do |format|
      if @unit_class.save
        format.html { redirect_to @unit_class, notice: 'Unit class was successfully created.' }
        format.json { render json: @unit_class, status: :created, location: @unit_class }
      else
        format.html { render action: "new" }
        format.json { render json: @unit_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unit_classes/1
  # PUT /unit_classes/1.json
  def update
    @unit_class = UnitClass.find(params[:id])

    respond_to do |format|
      if @unit_class.update_attributes(params[:unit_class])
        format.html { redirect_to @unit_class, notice: 'Unit class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_classes/1
  # DELETE /unit_classes/1.json
  def destroy
    @unit_class = UnitClass.find(params[:id])
    @unit_class.destroy

    respond_to do |format|
      format.html { redirect_to unit_classes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unit_classes_helper.rb
module UnitClassesHelper
end

app/views/unit_classes/_form.html.erb
<%= form_for(@unit_class) do |f| %>
  <% if @unit_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit_class.errors.count, "error") %> prohibited this unit_class from being saved:</h2>

      <ul>
      <% @unit_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_classes/edit.html.erb
<h1>Editing unit_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit_class %> |
<%= link_to 'Back', unit_classes_path %>

app/views/unit_classes/index.html.erb
<h1>Listing unit_classes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unit_classes.each do |unit_class| %>
  <tr>
    <td><%= unit_class.name %></td>
    <td><%= link_to 'Show', unit_class %></td>
    <td><%= link_to 'Edit', edit_unit_class_path(unit_class) %></td>
    <td><%= link_to 'Destroy', unit_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit class', new_unit_class_path %>

app/views/unit_classes/new.html.erb
<h1>New unit_class</h1>

<%= render 'form' %>

<%= link_to 'Back', unit_classes_path %>

app/views/unit_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unit_class.name %>
</p>


<%= link_to 'Edit', edit_unit_class_path(@unit_class) %> |
<%= link_to 'Back', unit_classes_path %>