config/routes.rb
Wwii::Application.routes.draw do

  root :to => 'Campaigns#index'

  get "login" => "Sessions#new", as:"login"

  post "login" => "Sessions#create"

  delete "logout"=>"Sessions#destroy", as:"logout"

  get "logout"=>"Sessions#destroy"
  resources :icons
  resources :users
  resources :unit_classes
  resources :operations
  resources :campaigns
  resources :units
  resources :events
  resources :countries
  resources :event_types

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :operations
  has_many :events, :through => :operations

  validates_presence_of :name
  validates_uniqueness_of :name

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name, :old_id, :flag_path

  has_many :units
  has_many :events, :through=>:units

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event_date, :name, :lat, :lng, :gmaps , :old_id, :unique_id, :address, :unit_id, :operation_id, :country_id, :event_type_id, :description

  belongs_to :unit
  belongs_to :operation
  belongs_to :country
  belongs_to :event_type

  validates_presence_of :name, :event_date

  acts_as_gmappable :process_geocoding => :geocode?,:lat=>'lat', :lng=>'lng',:address => "address"

  scope :no_planes, lambda { where("event_type_id != ?",EventType.find_by_name("Plane Crash").id).order('event_date asc')}

  scope :with_dates, lambda { where("event_date IS NOT null")}

  def date_formated
    (event_date.strftime('%a, %b %e %Y') unless event_date.nil?) || ""
  end

  def flag_path
      (country.flag_path unless country.nil?) || (unit.country.flag_path unless unit.nil? || unit.country.nil?) || nil
  end

  def calculate_country
    self.unit.country || self.country
  end

  def geocode?
    if !lat.blank? && !lat.blank?
      false
    elsif (lat.blank? || lng.blank?) && !address.blank?
      true
    elsif address_changed?
      true
    else
      false
    end
  end

  def location
     return {lat: lat, lng: lng} unless lat.nil? || lng.nil?
  end

  def gmaps4rails_title
      return event_date.strftime("%b %e %Y") unless event_date.nil?
  end

  def marker_picture
    if self.unit.present? && self.unit.icon.present?
      path = self.unit.icon.path
      folder_path = path.split("_")
      size = folder_path.delete_at(-1).split(".")[0].to_i
      folder_path = "/assets/" + path
      {
        :picture => folder_path,
        :width => size,
        :height => size,
        :marker_anchor => [ size/2, size]
      }
    else
      {
        :picture => "/assets/allies_infantry/allies_infantry_24.png",
        :width => 24,
        :height => 24,
        :marker_anchor => [ 12, 24]
      }
    end
  end

end

app/models/event_attribute.rb
class EventAttribute < ActiveRecord::Base
  attr_accessible :event_id, :unit_id, :country_id, :operation_id

end

app/models/event_date.rb
class EventDate < ActiveRecord::Base
  attr_accessible :old_id, :name
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  attr_accessible :name
end

app/models/icon.rb
class Icon < ActiveRecord::Base
  attr_accessible :name, :path
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  attr_accessible :name, :old_id, :campaign_id, :start_date, :end_date, :description, :active

  belongs_to :campaign

  has_many :events

  validates_presence_of :name
  validates_uniqueness_of :name

  def self.events?
    Operation.where(active:true).order('name asc')
  end

  def filtered(min=nil,max=nil)
    if min.nil? && max.nil?
      self.events.includes(:unit,:country).no_planes.order('event_date asc')
    elsif min.nil?
      self.events.includes(:unit,:country).no_planes.where("event_date <= ?",max).order('event_date asc')
    elsif max.nil?
      self.events.includes(:unit,:country).no_planes.where("event_date >= ?",min).order('event_date asc')
    else
      self.events.includes(:unit,:country).no_planes.where("event_date between ? and ? ",min,max).order('event_date asc')
    end
  end

  def units
    units = self.events.collect do |event|
      if event.unit.any?
        event.unit
      else
        nil
      end
    end
    return units.flatten.uniq.compact
  end

  def self.data
    data = Operation.events?.map do |operation|
      {
        :id => operation.id,
        :boundaries => operation.boundaries
      }
    end
    return data
  end

  def self.list
    operations = Operation.all.map do |operation|
      {:name=>'Operation ' + operation.name, :id=>operation.id}
    end
  end

  def date_formated(date_object)
    return date_object.strftime('%b %Y') unless date_object == nil
  end

  def first_date
    events.with_dates.no_planes.first.event_date.beginning_of_day || start_date.beginning_of_day || Date.parse('1940-01-01')
  end

  def last_date
    events.with_dates.no_planes.last.event_date.end_of_day || end_date.end_of_day || Date.parse('1949-12-31')
  end

  def boundaries
    locations = self.events.collect { |event| event.location }
    return locations.uniq
  end

  def to_param
    "#{id}-operation-#{name.parameterize}"
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :old_id, :unit_type_id, :country_id, :unit_class_id, :icon_id

  belongs_to :unit_type
  belongs_to :country
  has_many :events
  belongs_to :unit_class
  belongs_to :icon

  validates_presence_of :name
  validates_uniqueness_of :name

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/unit_class.rb
class UnitClass < ActiveRecord::Base
  attr_accessible :name, :marker_path
end

app/models/unit_type.rb
class UnitType < ActiveRecord::Base
  attr_accessible :name

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation

  has_secure_password
end

app/models/wiki.rb
class Wiki
    require 'wikipedia'
    #pass in the topic
    def initialize(topic,prepend="")
      @wiki ||= Wikipedia.find(prepend + topic)
    end

    def full_text
      if @wiki && h = @wiki.sanitized_content
        paragraphs = h.scan('<p>').count
        topics = h.scan(/==(.+)==/).count
        images = @wiki.image_urls
        if h.scan(/==\s*Notes\s*==/).count > 0
          h = h.split(/==\s*Notes\s*==/).reverse.pop
        end
        if h.scan(/==\s*References\s*==/).count > 0
          h = h.split(/==\s*References\s*==/).reverse.pop
        end
        if h.scan(/==\s*See also\s*==/).count > 0
          h = h.split(/==\s*See also\s*==/).reverse.pop
        end
        if h.scan(/==\s*Footnotes\s*==/).count > 0
          h = h.split(/==\s*Footnotes\s*==/).reverse.pop
        end
        h.gsub!(/====\s*(.+)\s*====/,'<i>\1</i>')
        h.gsub!(/===\s*(.+)\s*===/,'<b>\1</b>')
        h.sub!(/<p>\s*==(.+)\s*==/,'<p class="clearfix"></p><a class="main-list main-list-link" id="wiki_div_link_0" data-toggle="collapse" data-target="#wiki_div_0">\1</a><div id="wiki_div_0" class="collapse"><p>')
        index = 1
        if topics > 0
          while index < topics do
            h.sub!(/<p>==\s*(.+)\s*==/,'</p></div><a class="main-list main-list-link" id="wiki_div_link_'+ index.to_s + '" data-toggle="collapse" data-target="#wiki_div_'+index.to_s+'">\1</a><div id="wiki_div_'+index.to_s+'" class="collapse"><p>')
            index += 1
          end
          h = h + "</p></div>"
        end
        index = 0
        while images.present? && images.count >= 0
          image = images.delete_at(0)
          (align = "left" if images.count.odd?) || align = "right"
          h.sub!("<p>","<p class=\"clearfix\"><div id=\"wiki_image_#{index}\" class=\"modal hide fade\" tabindex=\"-1\"><div class=\"modal-header\"><button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">x</button><h3>&nbsp;</h3></div><div class=\"modal-body\"><img src=\"#{image}\"/></div></div><img onclick=\"$('#wiki_image_#{index}').modal('toggle')\" class=\"img-polaroid\" src=\"#{image}\" width=150 align=\"#{align}\"/>")
          index += 1
        end
        h
      else
        "No Wikipedia Content Found"
      end
    end

    def summary
      @wiki.sanitized_content.slice(0..275) + '...</p>' unless @wiki.nil?
    end
  end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>World War II War Atlas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "//fonts.googleapis.com/css?family=Montserrat:400,700|Gentium+Book+Basic", :media => "all" %>
  <%= stylesheet_link_tag    "//code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-39485921-1', 'waratlas.org');
    ga('send', 'pageview');
  </script>
 </head>
<body>
  <div id="primary-menu">
    <% if authorized? %>
      <%= link_to "Campaigns", campaigns_path, class:"primary-menu-link" %> |
      <%= link_to "Operations", operations_path, class:"primary-menu-link" %> |
      <%= link_to "Events", events_path, class:"primary-menu-link" %> |
      <%= link_to "Countries", countries_path, class:"primary-menu-link" %> |
      <%= link_to "Units", units_path, class:"primary-menu-link" %> |
      <%= link_to "Icons", icons_path, class:"primary-menu-link" %> |
      <%= link_to "Event Types", event_types_path, class:"primary-menu-link" %> |
      <%= link_to "Users", users_path, class:"primary-menu-link" %> |
      <%= link_to "Logout", logout_url, method:"delete", class:"primary-menu-link" %>
    <% else %>
      <%= link_to "Operations", campaigns_path, class:"primary-menu-link" %>
      <%= link_to "Countries", countries_path, class:"primary-menu-link" %>
    <% end %>
  </div>
  <% if @controller === "events" && @action === "edit" %>
    <%= gmaps(
      "markers" => {
        "data" => @markers,
        "options" => {
          "do_clustering" => false
        },
        "map_options" => {
          "draggable" => true
        }
      }
    ) %>
  <% elsif @controller === "operations" %>
    <%= gmaps(
      "markers" => {
        "data" => @markers,
        "options" => {
          "do_clustering" => false
        }
      },
      "map_options" => {
        "draggable" => true,
        "zoom" => 7,
        "auto_adjust" => true,
        "auto_zoom" => true,
        "bounds" => [],
        "center_latitude" => nil,
        "center_longitude" => nil
      }
    ) %>
  <% else %>
    <%= gmaps("markers" => {"data" => @markers, "options"=>{"do_clustering"=>true}}) %>
  <% end %>

  <div id="main">
    <%= yield %>
  </div>

  <script type="text/html" class="ww_template" id="loader">
    <div class="loader-container">
      <img class="loader" src="/assets/main-loader.gif" alt="Loading" />
    </div>
  </script>

  <%= yield :scripts %>
  <%= yield :scripts_callback %>
  <%= yield :slider %>

  <script>
  var resizeMainContainer = function() {
      var $container = $( '#main .main-container' ),
        documentHeight = $( document ).outerHeight();

      $container.css( 'height', ( documentHeight - $container.offset().top - 15 ) + 'px' ); // 15 for padding
    },
    i;

  for ( i = 0; i < ww.initQueue.length; i++ ) {
    ww.initQueue[ i ]();
  }

  for ( i = 0; i < ww.queueAtEnd.length; i++ ) {
    ww.queueAtEnd[ i ]();
  }

  $( window ).on( 'resize', resizeMainContainer );
  resizeMainContainer();
  </script>